creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - age1jduzksjl7nsegr9h5mngfpthzwc52tcj4f82cyjert9qsr4rxufs96wt45
        - age1lj9zvte2dr95m2anh6xh4kydrcvh5gmcuxvdsgs0e3pdwks4de5q8a673z
